name: Opam
on:
  push:
    branches: [main]
  pull_request:

# This will cancel previous runs when a branch or PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        ocaml-compiler: [4.14.1, 5.3.0]

    steps:
      - name: Setup node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "22"
          check-latest: true

      - name: Checkout project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true

      - uses: cygwin/cygwin-install-action@v6
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          add-to-path: 'true'
          packages: |
            mingw64-i686-gcc-core
            mingw64-i686-gcc-g++
            mingw64-x86_64-gcc-core
            mingw64-x86_64-gcc-g++
            make
            cmake

      - name: Setup OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@93303b622b2522e4411e295f9e77411a24912ac7 # v3.9.0
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Inspect depexts
        run: |
          opam exec -- which cmake
          opam exec -- which gcc
          opam exec -- which g++
          opam exec -- gcc --version
          opam exec -- g++ --version

      - name: Install local dependencies
        run: opam install . --deps-only --with-test

      - name: Build project
        run: opam exec -- dune build

      - name: Run tests
        run: opam exec -- dune runtest --display=short
