name: Opam
on:
  - push
  - pull_request

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ocaml-compiler: [4.12.1, 4.13.1, 4.14.0]

    steps:
      - name: Checkout project
        uses: actions/checkout@v3.1.0
        with:
          submodules: "recursive"

      - name: Hack Git CRLF for ocaml/setup-ocaml with MinGW and upstream repository
        if: ${{ startsWith(matrix.os, 'windows-') }}
        run: |
          git config --system core.autocrlf input

      - name: Setup OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-repositories: |
            default: https://github.com/fdopen/opam-repository-mingw.git#opam2
            upstream: https://github.com/ocaml/opam-repository.git

      - name: Inspect depexts
        run: |
          opam exec -- which cmake

      - name: Install local dependencies
        run: opam install . --deps-only --with-test

      - name: Build project
        run: opam exec -- dune build

      - name: Run tests
        run: opam exec -- dune runtest --display=short
